# data : pubmed, citeseer, cora, Cornell, Texas, Wisconsin, Photo, Computers 
data:
  data: citeseer
  dir: './data'
  nfeat: 3703
  nlabel: 6

model:
  model: GCNConv
  denoise_model: v1
  nhid: 64
  num_layers: 2
  num_linears: 1

train:
  num_epochs: 1000
  lr: 0.01
  weight_decay: 0.01
  lr_schedule: False
  lr_decay: 0.999999
  grad_norm: 1